# Generated by Django 5.2 on 2025-10-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    # This migration referenced a 'Sector' model which does not exist anymore.
    # To keep the migration graph consistent with the current models, we
    # neutralize this migration to a no-op.
    operations = []
