# Generated by Django 5.2 on 2025-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_governmentscheme_options_alter_sector_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('scraped', 'Scraped')], default='manual', help_text='How this scheme entry was created', max_length=20),
        ),
    ]
