# Generated by Django 4.2.14 on 2024-07-29 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_governmentscheme_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # FIX: Implement robust SQL to drop the 'origin' column only if it exists.
        # This resolves the 'column "origin" of relation "schemes" does not exist' error.
        migrations.RunSQL(
            sql="ALTER TABLE schemes DROP COLUMN IF EXISTS origin;",
            # Added a reverse operation for safe rollbacks, creating the column as nullable.
            reverse_sql="ALTER TABLE schemes ADD COLUMN origin varchar(255) NULL;"
        ),
        
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('scheme_recommendation', 'Scheme Recommendation'), ('scheme_update', 'Scheme Update'), ('application_deadline', 'Application Deadline'), ('new_scheme', 'New Scheme'), ('system', 'System Message')], max_length=30)),
                ('scheme_id', models.CharField(blank=True, help_text='Related scheme ID', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_ea6762_idx'), models.Index(fields=['notification_type'], name='user_notifi_notific_17530c_idx'), models.Index(fields=['created_at'], name='user_notifi_created_0a808a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Mobile number for notifications', max_length=15, null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('education', models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('higher_secondary', 'Higher Secondary'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('other', 'Other')], max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self Employed'), ('student', 'Student'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('other', 'Other')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, help_text='State of residence', max_length=100, null=True)),
                ('district', models.CharField(blank=True, help_text='District of residence', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, help_text='PIN code', max_length=10, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi')], default='en', help_text='Preferred interface language', max_length=10)),
                ('interested_sectors', models.JSONField(default=list, help_text='List of sectors user is interested in')),
                ('notification_preferences', models.JSONField(default=dict, help_text='Notification settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether user profile is verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='govt_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['state'], name='user_profil_state_69b9fb_idx'), models.Index(fields=['preferred_language'], name='user_profil_preferr_b7c280_idx'), models.Index(fields=['is_verified'], name='user_profil_is_veri_0e3ed5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSchemeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(help_text='MongoDB scheme ID', max_length=100)),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('applied', 'Applied'), ('bookmarked', 'Bookmarked'), ('shared', 'Shared'), ('inquired', 'Inquired')], max_length=20)),
                ('interaction_data', models.JSONField(default=dict, help_text='Additional interaction details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scheme_interactions',
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='user_scheme_user_id_f16272_idx'), models.Index(fields=['scheme_id'], name='user_scheme_scheme__99ba21_idx'), models.Index(fields=['created_at'], name='user_scheme_created_717e7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Search query text')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('pa', 'Punjabi')], default='en', max_length=10)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('clicked_schemes', models.JSONField(default=list, help_text='IDs of schemes user clicked on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_search_user_id_216b10_idx'), models.Index(fields=['language'], name='user_search_languag_ceb96c_idx')],
            },
        ),
    ]