# Generated by Django 5.2.8 on 2025-11-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_governmentscheme_origin_usernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentscheme',
            name='origin',
        ),
    ]
