# Generated by Django 5.2.8 on 2025-11-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_governmentscheme_origin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='governmentscheme',
            new_name='scheme_sector_01570a_idx',
            old_name='schemes_sector_7428f1_idx',
        ),
        migrations.RenameIndex(
            model_name='governmentscheme',
            new_name='scheme_governm_07c6f7_idx',
            old_name='schemes_governm_f9420f_idx',
        ),
        migrations.RenameIndex(
            model_name='governmentscheme',
            new_name='scheme_state_75cd2f_idx',
            old_name='schemes_state_a91b26_idx',
        ),
        migrations.RenameIndex(
            model_name='governmentscheme',
            new_name='scheme_languag_6f9abc_idx',
            old_name='schemes_languag_ce9c18_idx',
        ),
        migrations.RenameIndex(
            model_name='governmentscheme',
            new_name='scheme_is_acti_ae36f8_idx',
            old_name='schemes_is_acti_8232d5_idx',
        ),
        migrations.AlterModelTable(
            name='governmentscheme',
            table='scheme',
        ),
    ]
