# Generated by Django 5.2 on 2025-11-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_schemes_sector_7428f1_idx_scheme_sector_01570a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentscheme',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Brief description', max_length=1000, null=True),
        ),
    ]
