# Generated by Django 5.2 on 2025-11-15 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_governmentscheme_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sector',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='governmentscheme',
            new_name='scheme_sector__23ff9e_idx',
            old_name='scheme_sector_01570a_idx',
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Brief description', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.sector'),
        ),
    ]
