# Generated by Django 5.2 on 2025-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='origin',
            field=models.CharField(default='bulk-import', help_text="Origin/source of this scheme record (e.g., 'web-scrape', 'bulk-import', 'manual-entry')", max_length=64),
        ),
    ]
