# Generated by Django 5.2 on 2025-11-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_pgvector_embedding'),
        ('chatbot', '0009_governmentscheme_origin'),
    ]

    operations = [
    ]
