# Generated by Django 5.2 on 2025-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_merge_20251120_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='application_process_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations of application process'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations of benefits'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility_criteria_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations of eligibility criteria'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='financial_assistance_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations of financial assistance'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='short_description_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations of short description'),
        ),
    ]
