# Generated by Django 5.2 on 2025-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_governmentscheme_application_process_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('scraped', 'Scraped')], default='manual', help_text='Whether this scheme was manually added or scraped from a website', max_length=20),
        ),
    ]
