# Generated by Django 5.2 on 2025-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_governmentscheme_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scraped_scheme',
                'ordering': ['-created_at'],
            },
        ),
    ]
